#spring:
#  mvc:
#      静态资源访问前缀：当前项目 + static-path-pattern + 静态资源名 = 静态资源文件夹下找,加上这个配置后 默认的首页和Favicon会失效
#      static-path-pattern: /res/**
#  web:
#    resources:
#      指定默认的静态资源路径，配置后只会从该目录下查找静态资源
#      static-locations: [classpath:/hh/]